---
# handlers file for base
- name: restart vip
  ansible.builtin.systemd:
    name: vip-manager
    state: restarted
    enabled: yes

- name: restart patroni
  ansible.builtin.systemd:
    name: patroni
    state: restarted
    enabled: yes
 