---
- name: playbook for nfs
  hosts: 
    - nfs
  roles: 
    - roles/nfs
  tags: playbook
  
- name: prepare pg1/pg2 postgresql14
  hosts: 
    - pgsql
  roles:
    - roles/prepare-pgsql
  tags: pb-prepare-pgsql

#-----после проработки playbook нужно зайти на nfs и запустить systemctl start nfs
#=====А после выполняем команды, которые находятся в roles/repare-pgsql/tasks/main

 

