- name: Playbook to setup all the backend webservers
  hosts: webservers
  roles: 
    - roles/webserver_role

- name: Play to setup the loadbalancer
  hosts: balance
  roles:
    - roles/lb_role
      
 

      
      
 
